BEGIN TRANSACTION;
CREATE TABLE images (
      url TEXT PRIMARY KEY, path TEXT NOT NULL);
INSERT INTO "images" VALUES('https://ioma-paris.com/cdn/shop/files/creme-sublime-revitalisante-creme-anti-age-packshot-IOMA.jpg?v=1782462754&width=1000','assets/products/creme-sublime-revitalisante.jpg');
INSERT INTO "images" VALUES('https://ioma-paris.com/cdn/shop/files/cc-gel-soin-teinte-eclat-parfait-cc-creme-packshot-IOMA.jpg?v=1782400396&width=1000','assets/products/cc-gel.jpg');
INSERT INTO "images" VALUES('https://ioma-paris.com/cdn/shop/files/creme-genereuse-contour-des-yeux-contour-des-yeux-anti-age-packshot-IOMA.jpg?v=1782401105&width=1000','assets/products/creme-genereuse-contour-des-yeux.jpg');
CREATE TABLE product_images (
      page_url TEXT, name TEXT, image_url TEXT,
      PRIMARY KEY (page_url, name, image_url));
INSERT INTO "product_images" VALUES('urn:agent-beauty:manual:ioma:creme-sublime-revitalisante','Crème Sublime Revitalisante – Soin anti-âge expert','https://ioma-paris.com/cdn/shop/files/creme-sublime-revitalisante-creme-anti-age-packshot-IOMA.jpg?v=1782462754&width=1000');
INSERT INTO "product_images" VALUES('urn:agent-beauty:manual:ioma:cc-gel','CC Gel – Crème Soin Teinté Eclat Parfait','https://ioma-paris.com/cdn/shop/files/cc-gel-soin-teinte-eclat-parfait-cc-creme-packshot-IOMA.jpg?v=1782400396&width=1000');
INSERT INTO "product_images" VALUES('urn:agent-beauty:manual:ioma:creme-genereuse-contour-des-yeux','Crème Généreuse Contour des Yeux','https://ioma-paris.com/cdn/shop/files/creme-genereuse-contour-des-yeux-contour-des-yeux-anti-age-packshot-IOMA.jpg?v=1782401105&width=1000');
CREATE TABLE products (
      page_url TEXT NOT NULL, name TEXT NOT NULL, sku TEXT,
      description TEXT, json_ld TEXT NOT NULL,
      collected_at TEXT DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (page_url, name));
INSERT INTO "products" VALUES('urn:agent-beauty:manual:ioma:creme-sublime-revitalisante','Crème Sublime Revitalisante – Soin anti-âge expert',NULL,'La Crème Sublime Revitalisante fait pénétrer les actifs rapidement et nourrit la peau du visage en profondeur. Elle redensifie les volumes et redessine les contours. La barrière cutanée est renforcée et le soin stimule la production de collagène pour une peau plus ferme.','{"@context": "https://schema.org", "@type": "Product", "name": "Crème Sublime Revitalisante – Soin anti-âge expert", "brand": {"@type": "Brand", "name": "IOMA Paris"}, "description": "La Crème Sublime Revitalisante fait pénétrer les actifs rapidement et nourrit la peau du visage en profondeur. Elle redensifie les volumes et redessine les contours. La barrière cutanée est renforcée et le soin stimule la production de collagène pour une peau plus ferme.", "offers": {"@type": "Offer", "price": "149.00", "priceCurrency": "EUR"}, "additionalProperty": [{"name": "Gamme", "value": "3 - Renew"}, {"name": "Badge", "value": "MEILLEURE VENTE"}, {"name": "Prix pour 100 ml", "value": "298.00 EUR"}, {"name": "Points de fidélité", "value": 149}], "source": "user-provided chat", "image_status": "stored locally in project assets", "editorial": {"theme": "renew", "claim_it": "Nutre la pelle in profondità. Per una pelle più soda."}, "local_image_path": "assets/products/creme-sublime-revitalisante.jpg", "image_source_url": "https://ioma-paris.com/cdn/shop/files/creme-sublime-revitalisante-creme-anti-age-packshot-IOMA.jpg?v=1782462754&width=1000"}','2026-10-07 15:36:19');
INSERT INTO "products" VALUES('urn:agent-beauty:manual:ioma:cc-gel','CC Gel – Crème Soin Teinté Eclat Parfait',NULL,'Ce soin teinté apporte un effet bonne mine immédiat à la couvrance naturelle. Sa teinte universelle s’adapte à la perfection à toutes les carnations en créant un teint halé sur-mesure. Ce perfecteur de teint est enrichi en principes actifs hydratants et protecteurs pour une peau lissée et unifiée tout en réhaussant le teint.','{"@context": "https://schema.org", "@type": "Product", "name": "CC Gel – Crème Soin Teinté Eclat Parfait", "brand": {"@type": "Brand", "name": "IOMA Paris"}, "description": "Ce soin teinté apporte un effet bonne mine immédiat à la couvrance naturelle. Sa teinte universelle s’adapte à la perfection à toutes les carnations en créant un teint halé sur-mesure. Ce perfecteur de teint est enrichi en principes actifs hydratants et protecteurs pour une peau lissée et unifiée tout en réhaussant le teint.", "offers": {"@type": "Offer", "price": "42.00", "priceCurrency": "EUR"}, "additionalProperty": [{"name": "Gamme", "value": "2 - Energize"}, {"name": "Badge", "value": "MEILLEURE VENTE"}, {"name": "Prix pour 100 ml", "value": "140.00 EUR"}], "source": "user-provided chat", "image_status": "stored locally in project assets", "editorial": {"theme": "glow", "claim_it": "Un incarnato luminoso, dalla coprenza naturale."}, "local_image_path": "assets/products/cc-gel.jpg", "image_source_url": "https://ioma-paris.com/cdn/shop/files/cc-gel-soin-teinte-eclat-parfait-cc-creme-packshot-IOMA.jpg?v=1782400396&width=1000"}','2026-10-07 15:36:47');
INSERT INTO "products" VALUES('urn:agent-beauty:manual:ioma:creme-genereuse-contour-des-yeux','Crème Généreuse Contour des Yeux',NULL,'Ce soin contour des yeux anti-âge global est particulièrement riche en actifs : il lisse les rides et ridules, et aide à prévenir leur apparition.

La peau sensible de cette zone gagne en fermeté grâce à un complexe d''actifs lissant et régénérants. Les rides d''expressions sont estompées, l''apparition des rides profondes est retardée. La peau semple plus jeune et raffermie.','{"@context": "https://schema.org", "@type": "Product", "name": "Crème Généreuse Contour des Yeux", "brand": {"@type": "Brand", "name": "IOMA Paris"}, "description": "Ce soin contour des yeux anti-âge global est particulièrement riche en actifs : il lisse les rides et ridules, et aide à prévenir leur apparition.\n\nLa peau sensible de cette zone gagne en fermeté grâce à un complexe d''actifs lissant et régénérants. Les rides d''expressions sont estompées, l''apparition des rides profondes est retardée. La peau semple plus jeune et raffermie.", "offers": {"@type": "Offer", "price": "69.00", "priceCurrency": "EUR"}, "additionalProperty": [{"name": "Gamme", "value": "3 - Renew"}, {"name": "Badge", "value": "MEILLEURE VENTE"}, {"name": "Prix pour 100 ml", "value": "460.00 EUR"}, {"name": "Points de fidélité", "value": 69}, {"name": "Contenance", "value": "15 ml / 0.5 fl. oz."}], "editorial": {"theme": "renew", "claim_it": "Leviga rughe e linee sottili del contorno occhi."}, "source": "user-provided chat", "image_status": "stored locally in project assets", "local_image_path": "assets/products/creme-genereuse-contour-des-yeux.jpg", "image_source_url": "https://ioma-paris.com/cdn/shop/files/creme-genereuse-contour-des-yeux-contour-des-yeux-anti-age-packshot-IOMA.jpg?v=1782401105&width=1000"}','2026-10-07 15:40:33');
COMMIT;
